from django.urls import path

from apps.admin_api.views import (
    AppLoginView,
    AppForgotPasswordView,
    AppGameHistoryView,
    AppInvitationActionView,
    AppInvitationListCreateView,
    AppLiveMatchListView,
    AppMemberDetailView,
    AppMemberListView,
    AppMeView,
    AppNotificationListView,
    AppPublicBadgeListView,
    AppPublicRankingListView,
    AppPublicTournamentListView,
    AppRegisterView,
    AdminAuditLogListView,
    AdminBadgeListView,
    AdminDashboardView,
    AdminDisputeListView,
    AdminMemberListCreateView,
    AdminTournamentListCreateView,
    AdminLiveMatchListView,
    AdminNotificationListView,
    AdminRankingListView,
)


urlpatterns = [
    path("app/auth/register/", AppRegisterView.as_view(), name="app-auth-register"),
    path("app/auth/login/", AppLoginView.as_view(), name="app-auth-login"),
    path("app/auth/forgot-password/", AppForgotPasswordView.as_view(), name="app-auth-forgot-password"),
    path("app/me/", AppMeView.as_view(), name="app-me"),
    path("app/members/", AppMemberListView.as_view(), name="app-members"),
    path("app/members/<uuid:member_id>/", AppMemberDetailView.as_view(), name="app-member-detail"),
    path("app/tournaments/", AppPublicTournamentListView.as_view(), name="app-tournaments"),
    path("app/live-matches/", AppLiveMatchListView.as_view(), name="app-live-matches"),
    path("app/rankings/", AppPublicRankingListView.as_view(), name="app-rankings"),
    path("app/badges/", AppPublicBadgeListView.as_view(), name="app-badges"),
    path("app/notifications/", AppNotificationListView.as_view(), name="app-notifications"),
    path("app/invitations/<str:box>/", AppInvitationListCreateView.as_view(), name="app-invitations-list"),
    path("app/invitations/", AppInvitationListCreateView.as_view(), name="app-invitations-create"),
    path("app/invitations/<uuid:invitation_id>/<str:action>/", AppInvitationActionView.as_view(), name="app-invitations-action"),
    path("app/games/history/", AppGameHistoryView.as_view(), name="app-games-history"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/members/", AdminMemberListCreateView.as_view(), name="admin-members"),
    path("admin/tournaments/", AdminTournamentListCreateView.as_view(), name="admin-tournaments"),
    path("admin/live-matches/", AdminLiveMatchListView.as_view(), name="admin-live-matches"),
    path("admin/rankings/", AdminRankingListView.as_view(), name="admin-rankings"),
    path("admin/notifications/", AdminNotificationListView.as_view(), name="admin-notifications"),
    path("admin/disputes/", AdminDisputeListView.as_view(), name="admin-disputes"),
    path("admin/badges/", AdminBadgeListView.as_view(), name="admin-badges"),
    path("admin/audit-logs/", AdminAuditLogListView.as_view(), name="admin-audit-logs"),
]
