insert into public.badges (code, name, description, category, icon_path, points_threshold, sort_order, is_active)
values
('rank_novice_i','Novice I','Rang initial du club','rank','assets/badges/rank_novice_i.svg',0,10,true),
('rank_novice_ii','Novice II','Progression novice','rank','assets/badges/rank_novice_ii.svg',100,20,true),
('rank_novice_iii','Novice III','Progression novice confirmee','rank','assets/badges/rank_novice_iii.svg',200,30,true),
('rank_apprenti_i','Apprenti I','Premier palier apprenti','rank','assets/badges/rank_apprenti_i.svg',350,40,true),
('rank_apprenti_ii','Apprenti II','Progression apprenti','rank','assets/badges/rank_apprenti_ii.svg',500,50,true),
('rank_apprenti_iii','Apprenti III','Apprenti confirme','rank','assets/badges/rank_apprenti_iii.svg',700,60,true),
('rank_intermediaire_i','Intermediaire I','Palier intermediaire','rank','assets/badges/rank_intermediaire_i.svg',900,70,true),
('rank_intermediaire_ii','Intermediaire II','Progression intermediaire','rank','assets/badges/rank_intermediaire_ii.svg',1150,80,true),
('rank_intermediaire_iii','Intermediaire III','Intermediaire confirme','rank','assets/badges/rank_intermediaire_iii.svg',1400,90,true),
('rank_stratege_i','Stratege I','Debut du rang stratege','rank','assets/badges/rank_stratege_i.svg',1700,100,true),
('rank_stratege_ii','Stratege II','Progression stratege','rank','assets/badges/rank_stratege_ii.svg',2000,110,true),
('rank_stratege_iii','Stratege III','Stratege confirme','rank','assets/badges/rank_stratege_iii.svg',2300,120,true),
('rank_maitre_du_club','Maitre du Club','Elite du club','rank','assets/badges/rank_maitre_du_club.svg',2700,130,true),
('rank_grand_maitre_du_club','Grand Maitre du Club','Sommet competitif du club','rank','assets/badges/rank_grand_maitre_du_club.svg',3200,140,true),
('rank_legende','Legende','Rang legendaire du club','rank','assets/badges/rank_legende.svg',4000,150,true),
('first_win','Premiere victoire','Gagner sa premiere partie','achievement','assets/badges/first_win.svg',null,210,true),
('wins_10','10 victoires','Gagner 10 parties','achievement','assets/badges/wins_10.svg',null,220,true),
('wins_50','50 victoires','Gagner 50 parties','achievement','assets/badges/wins_50.svg',null,230,true),
('wins_100','100 victoires','Gagner 100 parties','achievement','assets/badges/wins_100.svg',null,240,true),
('streak_5','Serie de 5','Gagner 5 parties consecutives','achievement','assets/badges/streak_5.svg',null,250,true),
('tournament_champion','Champion de tournoi','Remporter un tournoi','competition','assets/badges/tournament_champion.svg',null,310,true),
('finalist','Finaliste','Atteindre une finale de tournoi','competition','assets/badges/finalist.svg',null,320,true),
('most_active_player','Joueur le plus actif','Participer regulierement aux activites','activity','assets/badges/most_active_player.svg',null,410,true),
('undefeated_month','Mois invaincu','Rester invaincu sur un mois','achievement','assets/badges/undefeated_month.svg',null,420,true),
('top_10_general','Top 10 general','Entrer dans le top 10 general','competition','assets/badges/top_10_general.svg',null,430,true),
('top_10_competition','Top 10 competition','Entrer dans le top 10 competition','competition','assets/badges/top_10_competition.svg',null,440,true),
('most_watched_game','Partie populaire','Jouer une partie tres suivie','activity','assets/badges/most_watched_game.svg',null,450,true)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  icon_path = excluded.icon_path,
  points_threshold = excluded.points_threshold,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
